### ISSUE TITLE
Question regarding the name of the output layer when converting .pt(ultralytics yolov3) to onnx

### ISSUE THREAD

**Issue by leeyunhome** [BobLd/YOLOv3MLNet#2]
Hello,
Thank you for sharing a great project.
When yolov3.pt is converted to onnx, you can check the output as 371, 391, output, not classes and boxes.

The output should come out as classes, boxes, and the question about this is:
Any advice would be appreciated.

You can check my situation at the following address.
https://github.com/ultralytics/yolov5/issues?q=is%3Aissue+is%3Aopen+onnx

Thank you.

**Comment by BobLd** [comment]
Hi @leeyunhome, checking from the screenshot of output [here](https://github.com/ultralytics/yolov5/issues/2131), your model is not ouputing classes and boxes, but feature maps (has commented in your other issue).

Please check my [YOLOV4 project](https://github.com/BobLd/YOLOv4MLNet) - It has the same kind of outputs. I think you will need to change the `shapes` array by `[] { 80, 40, 20}` - see [here](https://github.com/BobLd/YOLOv4MLNet/blob/374faa03640ade9d3992655a7d1d978faa3f5096/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L25)

For the post-processing, you can find an implementation on`nms` (non-max suppression) [here](https://github.com/BobLd/YOLOv4MLNet/blob/374faa03640ade9d3992655a7d1d978faa3f5096/YOLOv4MLNet/DataStructures/YoloV4Prediction.cs#L137-L167).
